<a href="https://colab.research.google.com/github/goeunleee/deeplearning_study/blob/master/rnn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

X = [] ; Y = []

# [ 0.0 , 0.1, 0.2  0.3]  => [ [],[],[],[]]
for i in range(6):
  lst = np.array ( range(i, i+4) ) / 10.0
  lst = lst.reshape((-1, 1))
  X.append(lst)
  Y.append( (i+4) / 10.0 )

X = np.array(X)  # list to numpy array
Y = np.array(Y)
print(X.shape, Y.shape) 




(6, 4, 1) (6,)


In [ ]:
##----------------------------
import tensorflow as tf

rnn1 = tf.keras.layers.SimpleRNN(units=10, activation="tanh", dtype="float64", 
                          return_sequences=False, input_shape=(4,1))(X)

rnn1.shape



TensorShape([6, 10])

In [ ]:
##---------------------------
den1 = tf.keras.layers.Dense(units=1, dtype="float64")(rnn1)
den1.shape
den1



<tf.Tensor: shape=(6, 1), dtype=float64, numpy=
array([[-0.00936892],
       [ 0.08409774],
       [ 0.16119414],
       [ 0.21966347],
       [ 0.26024956],
       [ 0.28503646]])>

In [ ]:


model = tf.keras.Sequential([
     tf.keras.layers.SimpleRNN(units=10, activation="tanh", dtype="float64", return_sequences=False, input_shape=(4,1)),
     tf.keras.layers.Dense(units=1, dtype="float64")                        
])

model.compile(optimizer="adam", loss="mse")
model.summary()


history = model.fit(X, Y, epochs=200, verbose=0)


pred1 = [[[0.9],[1.0],[1.1],[1.2]]]    #(1,4,1)  0.9 1.0 1.2 1.3  =>  ??
model.predict( pred1 )




Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_2 (SimpleRNN)     (None, 10)                120       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 131
Trainable params: 131
Non-trainable params: 0
_________________________________________________________________


array([[0.66472711]])

In [ ]:
##--------------------------
model = tf.keras.Sequential([
     tf.keras.layers.LSTM(units=10, activation="tanh", dtype="float64", return_sequences=False, input_shape=(4,1)),
     tf.keras.layers.Dense(units=1, dtype="float64")                        
])

model.compile(optimizer="adam", loss="mse")
model.summary()

history = model.fit(X, Y, epochs=200, verbose=0)


pred1 = [[[0.9],[1.0],[1.1],[1.2]]]    #(1,4,1)  0.9 1.0 1.2 1.3  =>  ??
model.predict( pred1 )


Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (LSTM)                  (None, 10)                480       
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 11        
Total params: 491
Trainable params: 491
Non-trainable params: 0
_________________________________________________________________


array([[1.06567329]])

In [ ]:
##---------------------------
import numpy as np

# 100개의 랜덤 값 생성
lst = np.random.rand(100)
lst



array([0.57091358, 0.66343595, 0.48531229, 0.94375638, 0.6437681 ,
       0.78645968, 0.24583193, 0.73844275, 0.79516669, 0.15369149,
       0.478967  , 0.26304593, 0.48911845, 0.72031429, 0.57090325,
       0.53579489, 0.01222372, 0.47256338, 0.86010732, 0.39391831,
       0.86241133, 0.8633014 , 0.22148979, 0.86820397, 0.1224302 ,
       0.95849061, 0.70103729, 0.82814074, 0.61113809, 0.57862357,
       0.08633488, 0.85110379, 0.39047927, 0.39768266, 0.53552569,
       0.94258018, 0.02657564, 0.28036893, 0.24724867, 0.84696808,
       0.23404332, 0.32780866, 0.7761516 , 0.17040937, 0.63467983,
       0.87514109, 0.77831423, 0.12483257, 0.53008543, 0.33028011,
       0.80055142, 0.83070037, 0.47235318, 0.31881047, 0.29412284,
       0.99003074, 0.08993369, 0.61078884, 0.3254343 , 0.29778292,
       0.26207978, 0.81138844, 0.11076695, 0.03032261, 0.64915726,
       0.05105303, 0.76262225, 0.31052181, 0.35528876, 0.37013562,
       0.48511981, 0.80750518, 0.0814671 , 0.96725345, 0.03535

In [ ]:
##---------------------------
# 숫자 2개 생성
idx = np.random.choice(100, 2, replace=False) #중복되지 않는 2개의 숫자 뽑기
idx



array([90, 96])

In [ ]:
##---------------------------
zeros = np.zeros(100) 
zeros[idx] = 1 




In [ ]:
##---------------------------
#a = np.array([[1,2,3,4.....], [1,0,1,0....]])

#b = np.prod(a, axis=0)
#np.sum( b)



In [ ]:
##---------------------------
#a= np.array([[1,0], [2,2], [].....[] ])
#c = np.prod(a, axis=1)
#c

##---------------------------

X = [] # 5000, 100, 2   [[0, 1.234343], [1,1.3434343],[],[]....]
Y = [] # 5000           [1,322442, 2.42442, 4.2424242 .........]

for i in range(5000):
  lst = np.random.rand(100)  # 100개의 랜덤 숫자 구하기
  idx = np.random.choice(100, 2, replace=False) # 중복되지 않는 2개의 정수 구하기

  zeros = np.zeros(100)     # 0으로 채워진 100개의 array 생성
  zeros[idx] = 1            # 2개만 1로 채우기

  b = np.array( list(zip(zeros, lst) ) )           #배열 합치기
  X.append(b)

  c = np.prod( lst[idx] ) # idx가 1에 해당하는 것만 꺼내서 곱하기 [1, 0.2422424 * 1, 0.354353]] 
  Y.append(c)

X = np.array(X)
Y = np.array(Y)
print(X.shape, Y.shape)

(5000, 100, 2) (5000,)
